### ISSUE TITLE
Hard to locate room id after room creation

### ISSUE THREAD

**Issue by nwhean** [neosizzle/ft_transcendence#17]
Currently, room id is displayed next to the room name as:
`room_name - room_id`

It would be better if it is changed to the following:
`room_name (room id: room_id)`
preferably with different font to allow for easy identification with a quick glance.

Nice to have: would be good if there's a prompt to show the room id and a room creation success message.

**Comment by PandieYay** [comment]
https://github.com/neosizzle/ft_transcendence/commit/682fe2d2bdf13e7638fd39108b370a24c5f5b786
