### ISSUE TITLE
Last user is unable to leave room

### ISSUE THREAD

**Issue by nwhean** [neosizzle/ft_transcendence#19]
> "We are programmed to receive
> You can check out any time you like
> But you can never leave"
> ~ Hotel California by The Eagles

Unable to leave room when I'm the only person in there.

Expected behavior: Allow last user to leave room, with the room deleted.

**Comment by neosizzle** [comment]
Issue patch pushed to commit https://github.com/neosizzle/ft_transcendence/commit/00634fe67887a2c99b44bb9c1f0adc267152ac48
