### ISSUE TITLE
Game module planning

### ISSUE THREAD

**Issue by neosizzle** [neosizzle/ft_transcendence#2]
Add your own tasks here!

**Comment by nwhean** [comment]
- [ ] Display: HTML Canvas?
- [ ] Keybinding: Up and Down keys
- [ ] Walls
- [ ] Ball object
- [ ] Paddle object
- [ ] Ball reflection mechanics: simple reflection, paddle location based (used by original Pong), paddle speed based (add spin to ball)
- [ ] Match-making system
- [ ] Customisation ideas: different map / wall layout, paddle direction, random power up collectibles, 3 or 4 player pong
- [ ] (Optional) Computer opponent: different levels of difficulties

**Comment by neosizzle** [comment]
evaled
