### ISSUE TITLE
Buggy "Edit room" feature

### ISSUE THREAD

**Issue by nwhean** [neosizzle/ft_transcendence#20]
1. After clicking the "Edit room" button, then clicking "Cancel" when the prompt shows up, it still brings my to the next prompt.
Expected behaviour: to terminate the editing.

1. When the 2nd prompt shows up, clicking "Cancel" will cause "Room details changes successfully".
Expected behaviour: to terminate the editing.

1. After Editing room details, the old room name is still displayed, unless the page is refreshed. 
Expected behaviour: the room name should change.
Quick hacky debug: just ask the browser to reload the page.

**Comment by neosizzle** [comment]
Issue patch pushed to commit https://github.com/neosizzle/ft_transcendence/commit/00634fe67887a2c99b44bb9c1f0adc267152ac48
