### ISSUE TITLE
Chat is not resetting after i leave the last room

### ISSUE THREAD

**Issue by neosizzle** [neosizzle/ft_transcendence#23]
The chat still remains from the last room even after I leave
Expected behavior : Chat area will be clear
Suggested fix : before calling the auth_net_get to get chat messages, check if activeroom is null. If it is, set activeroom messages to []

[chat not resetting.webm](https://user-images.githubusercontent.com/44501267/188320014-30d52fc1-3559-474f-91e5-f3dfe30ddb84.webm)

**Comment by PandieYay** [comment]
Fixed by setting activeRoomMessages to [] when leave button is pressed. Also made members gone when leaving
