### ISSUE TITLE
[CLARIFICATION ]Room scroll does not behave like infinite scroll upon room creation 

### ISSUE THREAD

**Issue by neosizzle** [neosizzle/ft_transcendence#24]
The infinite scroll is not applied when creating new rooms. Is this intentional by design?
[more than 5 rooms already.webm](https://user-images.githubusercontent.com/44501267/188320081-c2a269d4-7588-4e58-aa67-7672d43fc17d.webm)

**Comment by PandieYay** [comment]
Fixed, just add + 1 after creating a room. Also made activeRoomCount - 1 when leaving a room
