### ISSUE TITLE
Chat module development (backend and websocket)

### ISSUE THREAD

**Issue by neosizzle** [neosizzle/ft_transcendence#3]
Add your own tasks here!

**Comment by PandieYay** [comment]
- [ ] Add input box
- [ ] Learn how to use databases
- [ ] Implement chat with database
- [ ] Add user profile / pfp
- [ ] Add tailwind css

**Comment by neosizzle** [comment]
- [x] event for user create room
- [x] event for user join room
- [ ] event for user message
- [x] event for user leave
- [ ] event for user ban
- [ ] event for user kick
- [x] event for transfer ownership
- [ ] event for user mute
- [x] event for promote admin
- [x] event for demote admin
- [x] room resource
- [x] admin resource
- [ ] chat resource
- [x] member resource
- [ ] ban resource
- [ ] mute resource
